spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enalble: true
          lower-case-service-id: true

  output:
    ansi:
      enable: always

server:
  port: 8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40c{1.}){cyan} %clr(:){faint} %m%n%wEx"
